<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <SonarQubeExclude>true</SonarQubeExclude>
    <NoWarn>$(NoWarn);CA1062;CA1822;IDE0022;IDE0059;EnableGenerateDocumentationFile</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ComplexityAnalysis.Analyzers\ComplexityAnalysis.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
</Project>
