using System.Collections.Immutable;
using System.Reflection;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

using Xunit;

namespace ComplexityAnalysis.Analyzers.Tests;

public sealed class ComplexityAnalyzerTests
{
    private const string AnalyzerExecutionProbeId = "BIG9000";

    [Fact]
    public void Analyzer_can_be_instantiated()
    {
        DiagnosticAnalyzer analyzer = new ComplexityAnalyzer();

        ComplexityAnalyzer typedAnalyzer = Assert.IsType<ComplexityAnalyzer>(analyzer);
        Assert.NotNull(typedAnalyzer);
    }

    [Fact]
    public void SupportedDiagnostics_contains_exactly_the_phase_one_probe()
    {
        var analyzer = new ComplexityAnalyzer();

        DiagnosticDescriptor descriptor = Assert.Single(analyzer.SupportedDiagnostics);

        Assert.Equal(AnalyzerExecutionProbeId, descriptor.Id);
    }

    [Fact]
    public void AnalyzerExecutionProbe_has_the_expected_public_descriptor_metadata()
    {
        DiagnosticDescriptor descriptor = Assert.Single(new ComplexityAnalyzer().SupportedDiagnostics);

        Assert.Equal(AnalyzerExecutionProbeId, descriptor.Id);
        Assert.Equal(DiagnosticSeverity.Info, descriptor.DefaultSeverity);
        Assert.False(descriptor.IsEnabledByDefault);
    }

    [Fact]
    public async Task Analyzer_does_not_report_the_probe_when_it_is_not_enabled()
    {
        ImmutableArray<Diagnostic> diagnostics = await GetAnalyzerDiagnosticsAsync(
            """
            public sealed class Sample
            {
                public int M() => 42;
            }
            """);

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id == AnalyzerExecutionProbeId);
    }

    [Fact]
    public async Task Analyzer_reports_exactly_one_probe_per_compilation_when_explicitly_enabled()
    {
        ImmutableArray<Diagnostic> diagnostics = await GetAnalyzerDiagnosticsAsync(
            """
            public sealed class Sample
            {
                public int M() => 42;
            }
            """,
            enableProbe: true);

        Diagnostic diagnostic = Assert.Single(diagnostics, diagnostic => diagnostic.Id == AnalyzerExecutionProbeId);
        Assert.Equal(DiagnosticSeverity.Info, diagnostic.Severity);
    }

    [Fact]
    public async Task Analyzer_reports_only_one_probe_for_code_with_multiple_methods()
    {
        ImmutableArray<Diagnostic> diagnostics = await GetAnalyzerDiagnosticsAsync(
            """
            public sealed class Sample
            {
                public int First() => 1;
                public int Second() => 2;
                public int Third() => First() + Second();
            }
            """,
            enableProbe: true);

        _ = Assert.Single(diagnostics, diagnostic => diagnostic.Id == AnalyzerExecutionProbeId);
    }

    [Fact]
    public async Task Generated_code_does_not_change_probe_emission_behavior()
    {
        ImmutableArray<SyntaxTree> syntaxTrees =
        [
            Parse(
                """
                public sealed class UserCode
                {
                    public int M() => 42;
                }
                """),
            Parse(
                """
                // <auto-generated/>
                public sealed class GeneratedCode
                {
                    public int First() => 1;
                    public int Second() => 2;
                }
                """,
                "Generated.g.cs")
        ];

        ImmutableArray<Diagnostic> disabledDiagnostics = await GetAnalyzerDiagnosticsAsync(syntaxTrees);
        ImmutableArray<Diagnostic> enabledDiagnostics = await GetAnalyzerDiagnosticsAsync(syntaxTrees, enableProbe: true);

        Assert.DoesNotContain(disabledDiagnostics, diagnostic => diagnostic.Id == AnalyzerExecutionProbeId);
        _ = Assert.Single(enabledDiagnostics, diagnostic => diagnostic.Id == AnalyzerExecutionProbeId);
    }

    [Fact]
    public async Task Analyzer_runs_on_a_valid_csharp_compilation_without_throwing()
    {
        ImmutableArray<Diagnostic> diagnostics = await GetAnalyzerDiagnosticsAsync(
            """
            public sealed class Sample
            {
                public string M() => nameof(Sample);
            }
            """);

        Assert.Empty(diagnostics);
    }

    private static Task<ImmutableArray<Diagnostic>> GetAnalyzerDiagnosticsAsync(
        string source,
        bool enableProbe = false)
    {
        return GetAnalyzerDiagnosticsAsync([Parse(source)], enableProbe);
    }

    private static async Task<ImmutableArray<Diagnostic>> GetAnalyzerDiagnosticsAsync(
        ImmutableArray<SyntaxTree> syntaxTrees,
        bool enableProbe = false)
    {
        CSharpCompilation compilation = CreateCompilation(syntaxTrees, enableProbe);
        var analyzer = new ComplexityAnalyzer();
        ImmutableArray<DiagnosticAnalyzer> analyzers = [analyzer];
        CompilationWithAnalyzers compilationWithAnalyzers = compilation.WithAnalyzers(analyzers);

        return await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync();
    }

    private static CSharpCompilation CreateCompilation(
        ImmutableArray<SyntaxTree> syntaxTrees,
        bool enableProbe)
    {
        ImmutableDictionary<string, ReportDiagnostic> specificDiagnosticOptions = enableProbe
            ? [KeyValuePair.Create(AnalyzerExecutionProbeId, ReportDiagnostic.Info)]
            : [];

        var compilationOptions = new CSharpCompilationOptions(
            OutputKind.DynamicallyLinkedLibrary,
            specificDiagnosticOptions: specificDiagnosticOptions);

        return CSharpCompilation.Create(
            assemblyName: "AnalyzerInfrastructureTests",
            syntaxTrees: syntaxTrees,
            references: BasicReferences,
            options: compilationOptions);
    }

    private static SyntaxTree Parse(string source, string path = "Sample.cs")
    {
        return CSharpSyntaxTree.ParseText(source, path: path);
    }

    private static ImmutableArray<MetadataReference> BasicReferences
    {
        get;
    } =
        [
            MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Enumerable).GetTypeInfo().Assembly.Location)
        ];
}
